name: srinivasa_crm_new
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  alphabet_scroll_view: ^0.3.2
  animations: ^2.0.11
  azlistview: ^2.0.0
  badges: ^3.1.2
  bloc: ^8.1.2
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.3.0
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  dio: ^5.4.0
  double_tap_to_exit: ^1.0.1
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  excel: ^4.0.2
  file_picker: ^8.0.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.3
  flutter_polyline_points: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  flutter_timezone: ^3.0.1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  image_picker: ^1.1.2
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  location: ^6.0.0
  logger: ^2.0.2+1
  lottie: ^3.1.2
  mockito: ^5.4.4
  open_file: ^3.3.2
  package_info_plus: ^8.0.0
  page_transition: ^2.1.0
  paged_datatable: ^2.1.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  permission_handler: ^11.2.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  quickalert: ^1.1.0
  scrollable_positioned_list: ^0.2.3
  share_plus: ^10.0.2
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  upgrader: ^10.3.0
  uuid: ^4.4.0
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  pubspec_dependency_sorter: ^1.0.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/svg/
    - assets/lottie/
    - assets/png/
    - assets/jpg/
    - assets/icon/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
