// buttons.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../config/constants/app_styles.dart';

class CommonButton extends StatelessWidget {
  final VoidCallback callback;
  final bool? isRejectButton;
  final bool? isApproveButton;
  final String title;
  const CommonButton({
    super.key,
    required this.callback,
    this.isRejectButton,
    this.isApproveButton,
    required this.title,
  });

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      
        style: isApproveButton == true ? AppStyles.approveButtonStyle(context) : isRejectButton == true ? AppStyles.rejectButtonStyle(context) : AppStyles.buildElevatedButtonStyle(context),
        onPressed: callback,
        child: Text(
          title,
          style: TextStyle(
              fontWeight: FontWeight.bold,
              color: Colors.white,
              fontSize: 18.sp),
        ));
  }
}
