// buttons.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../config/constants/app_styles.dart';

class CommonButton extends StatelessWidget {
  final VoidCallback callback;
  final String title;
  const CommonButton({
    Key? key,
    required this.callback,
    required this.title,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
        style: AppStyles.buildElevatedButtonStyle(context),
        onPressed: callback,
        child: Text(
          title,
          style: TextStyle(
              fontWeight: FontWeight.bold,
              color: Colors.white,
              fontSize: 18.sp),
        ));
  }
}
