// text.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'common_error_text_widget.dart';
export 'common_heading_text_widget.dart';
export 'common_text_widget.dart';