// config.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'constants/constants.dart';
export 'locator/locator.dart';
export 'routes/routes.dart';
